NUM_GPUS: 128
MODEL:
  PRECISION: "bfloat16"
  WEIGHTS: "/share/project/panting/diffnext-main/models.t2i/scratch_d48w1024_256px"
  CONFIG: {
    "image_dim": 4,
    "image_size": [256, 256],
    "image_stride": 8,
    "text_token_dim": 2560,
    "text_token_len": 256,
    "video_base_size": [1, 8, 8],
    "image_base_size": [16, 16],
    "arch": ["vit_d16w1024", "vit_d32w1024", "mlp_d6w1024"],
  }
PIPELINE:
  TYPE: "nova_train_t2i"
  MODULES: {
    "scheduler": "/share/project/panting/mm_ckpt/nova_shared/scheduler/flow",
    "text_encoder": "/share/project/panting/mm_ckpt/nova_shared/text_encoder/phi2",
    "tokenizer": "/share/project/panting/mm_ckpt/nova_shared/tokenizer/phi2",
    "vae": "/share/project/panting/mm_ckpt/nova_shared/vae/sdxl",
    "model_index": "/share/project/panting/mm_ckpt/nova_shared/model_index/flow_sdxl_phi2_nova.json",
  }
SOLVER:
  BASE_LR: 0.0008
  WEIGHT_DECAY: 0.02
  WARM_UP_STEPS: 10000
  MAX_STEPS: 2500000
  EMA_EVERY: 100
  SNAPSHOT_EVERY: 5000
  SNAPSHOT_PREFIX: "sdxl28m_nova_d48w1024_256px"
TRAIN:
  DATASET: "/share/project/panting/share_datasets/emu3_sdxl256_train28m"
  LOADER: "vae_train"
  BATCH_SIZE: 32
  MODEL_EMA: 0.99
  CHECKPOINTING: 2
  NUM_THREADS: 8

